import { borderRadiuses, fontFamilys, fontSizes, textColors } from '../../../assets/styles/Theme';

export const styles = theme => ({
	wrapper: {
		width: '100vw',
		height: '100vh',
		display: 'flex',
		flexDirection: 'column',
		justifyContent: 'space-between',
	},
	formContainer: {
		zIndex: 10,
		height: '100%',
		position: 'fixed',
		left: 0,
		right: 0,
		top: 0,
		bottom: 0,
		margin: 0,
		overflowY: 'auto',
	},
	formView: {
		width: '270px',
		margin: '64px 10vw',
		padding: '32px',
		float: 'right',
		borderRadius: borderRadiuses.regular,
		boxShadow: '0px 4px 16px 0px rgba(73, 73, 73, 0.08)',
		[theme.breakpoints.down('sm')]: {
			marginRight: '50vw !important',
			transform: 'translate(50%,0)',
		},
	},
	formTitle: {
		fontFamily: fontFamilys.primary.primary,
		color: textColors.primary,
		fontSize: fontSizes.title,
		margin: 0,
		paddingBottom: 16,
	},
	inputLabel: {
		fontSize: fontSizes.primary,
		fontFamily: fontFamilys.primary.primary,
		color: textColors.primary,
		marginTop: 0,
		marginBottom: 8,
	},
	inputField: {
		fontFamily: fontFamilys.primary.primary,
		width: '100%',
		marginBottom: 32,
		borderRadius: 7,
		[`& fieldset`]: {
			border: 'none',
			borderRadius: '7px',
			boxShadow: '0px 4px 16px 0px rgba(73, 73, 73, 0.08)',
		},
		[`& input`]: {
			fontFamily: fontFamilys.primary.primary,
			padding: '18.5px 24px',
			color: textColors.primary,
			height: 4,
			fontSize: fontSizes.primary,
			'&::-webkit-input-placeholder': { opacity: 0.25 },
		},
		'&:hover': {
			boxShadow: '0px 4px 16px 0px rgba(73, 73, 73, 0.2)',
		},
	},
	formBtn: {
		width: '100%',
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
	},
	submitBtn: {
		fontWeight: 400,
		height: 41,
		marginTop: 16,
		fontSize: fontSizes.primary,
		fontFamily: fontFamilys.primary.primary,
		color: '#ffffff',
		minWidth: '50%',
		borderRadius: borderRadiuses.small,
		backgroundImage: 'linear-gradient(to bottom, #01b8fa, #267aff)',
		boxShadow: '0px 4px 16px 0px rgba(38, 122, 255, 0.5)',
		WebkitBoxShadow: '0px 4px 16px 0px rgba(38, 122, 255, 0.5)',
		MozBoxShadow: '0px 4px 16px 0px rgba(38, 122, 255, 0.5)',
		'&:hover': {
			boxShadow: '0px 4px 16px 0px rgba(38, 122, 255, 0.8)',
			WebkitBoxShadow: '0px 4px 16px 0px rgba(38, 122, 255, 0.8)',
			MozBoxShadow: '0px 4px 16px 0px rgba(38, 122, 255, 0.8)',
		},
		'&:focus': {
			boxShadow: '0px 4px 16px 0px rgba(38, 122, 255, 0.5)',
			WebkitBoxShadow: '0px 4px 16px 0px rgba(38, 122, 255, 0.5)',
			MozBoxShadow: '0px 4px 16px 0px rgba(38, 122, 255, 0.5)',
		},
	},
});